Checking that livestreamer is installed

diff --git a/home/.bin/twitch_notify b/home/.bin/twitch_notify
--- a/home/.bin/twitch_notify
+++ b/home/.bin/twitch_notify
@@ -24,7 +24,16 @@ then
   exit 1
 fi
 
+if [ ! -x "/usr/local/bin/livestreamer" ]
+then
+  echo
+  echo -e "${red}Error:${colorOff} livestreamer is not installed."
+  echo
+  exit 1
+fi
+
 jshon="/usr/local/bin/jshon"
+livestreamer="/usr/local/bin/livestreamer"
 
 if [ -e ${liveStreamerConfig} ]
 then
